version: 2.1
description: Creating an orb to build test and  coverage upload

orbs:
  my-orb:
    orbs:
      codecov: codecov/codecov@1.0.2
    executors:
      node_10:
        docker:
        - image: circleci/node:10    
    commands:
      build:
        steps:
         - checkout
         - run: yarn --no-progress --frozen-lockfile
      test-node-10:
        steps:
          - checkout
          # - restore-cache: *restore-cache
          - run: yarn --no-progress --frozen-lockfile
          # - save-cache: *save-cache
          - run: yarn test

    jobs:
      build_test:
        executor: node_10
        steps:
          - build
          - test-node-10
      coverage:
        executor: node_10
        steps:
          - codecov/upload:
              file: ./coverage

workflows:
  main:
    jobs:
      - my-orb/build_test
      - my-orb/coverage:
          requires:
            - my-orb/build_test
